dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  path: ^1.8.0
  qrscan: ^0.3.3

cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

